# Generated by Django 3.2.10 on 2023-08-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plogdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfname', models.CharField(blank=True, max_length=100, null=True)),
                ('plname', models.CharField(blank=True, max_length=500, null=True)),
                ('pbirthday', models.CharField(blank=True, max_length=500, null=True)),
                ('pgender', models.CharField(blank=True, max_length=500, null=True)),
                ('pemail', models.CharField(blank=True, max_length=500, null=True)),
                ('pphone', models.IntegerField(blank=True, null=True)),
                ('pqual', models.CharField(blank=True, max_length=500, null=True)),
                ('pskill', models.CharField(blank=True, max_length=500, null=True)),
                ('pcity', models.CharField(blank=True, max_length=500, null=True)),
                ('ppincode', models.IntegerField(blank=True, null=True)),
                ('pid', models.CharField(blank=True, max_length=500, null=True)),
                ('pfile', models.ImageField(blank=True, null=True, upload_to='pfile')),
                ('ppassword', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
