# Generated by Django 3.2.10 on 2023-08-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plogdb',
            name='pfile',
            field=models.ImageField(blank=True, null=True, upload_to='doc'),
        ),
    ]
