# Generated by Django 3.2.10 on 2023-08-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20230806_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='postdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atitle', models.CharField(blank=True, max_length=100, null=True)),
                ('adisc', models.CharField(blank=True, max_length=1000, null=True)),
                ('ars', models.IntegerField(blank=True, null=True)),
                ('aloc', models.CharField(blank=True, max_length=100, null=True)),
                ('acat', models.CharField(blank=True, max_length=500, null=True)),
                ('aphoto', models.ImageField(blank=True, null=True, upload_to='image')),
                ('adate', models.CharField(blank=True, max_length=100, null=True)),
                ('akey', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
