# Generated by Django 3.2.10 on 2023-08-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_postdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdb',
            name='ausername',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
